name: PR checks

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  terraform_lint:
    name: TF - Lint
    uses: ministryofjustice/opg-github-workflows/.github/workflows/linting-infrastructure-terraform.yml@13329175a5ceaf65ba4507d087f54a1c3b82c574 # tag=v1.11.0
    with:
      terraform_version: 1.1.2

  terratest:
    name: Run Terratest Tests
    runs-on: ubuntu-latest
    needs: terraform_lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # tag=v2.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::PLACEHOLDER:role/PLACEHOLDER
          role-duration-seconds: 2400
          role-session-name: PLACEHOLDER
      - name: Run Terratest
        run: |
          cd tests/
          go test -v -timeout 40m serverlessv2_psql_test.go
